<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Api Endpoints</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            header {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }
            .endpoint {
                color: #ad1315;
                font-size: 20px;
            }
            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 50px;
                font-weight: 200;
                margin-bottom: 0;
            }
            .endpoints {
                margin-bottom: 10px;
                margin-top: 10px;
            }
            ul {
                margin-top: 10px;
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Api Documentation</h1>
        </header>
        <div>
            <ul>
                <li><h3>Unprotected endpoins</h3></li>
                <div class="endpoints">
                    <span class="endpoint">Ping server</span><br/>
                    <strong>Method: </strong>GET<br/>
                    <strong>Url: </strong><a href="http://localhost/api/v1/ping">http://localhost/api/v1/ping</a>
                </div>
                <div class="endpoints">
                    <span class="endpoint">Generate token access</span><br/>
                    <strong>Method: </strong>POST<br/>
                    <strong>Url: </strong>http://localhost/api/v1/user/token
                </div>
            </ul>
            <ul>
                <li><h3>Protected endpoins</h3></li>
                <div class="endpoints">
                    <span class="endpoint">List Users</span><br/>
                    <strong>Method: </strong>GET<br/>
                    <strong>Url: </strong>http://localhost/api/v1/users</br>
                    <strong>Authorization: </strong>Bearer <i>token_access</i></a>
                </div>
                <div class="endpoints">
                <span class="endpoint">List Teams</span><br/>
                    <strong>Method: </strong>GET<br/>
                    <strong>Url: </strong>http://localhost/api/v1/teams</br>
                    <strong>Authorization: </strong>Bearer <i>* generated token access via /user/token endpoint</i>
                </div>
                <div class="endpoints">
                    <span class="endpoint">Player wellness</span><br/>
                    <strong>Method: </strong>GET<br/>
                    <strong>Url: </strong>http://localhost/api/v1/wellness/{user_id}/{player_id}</br>
                    <strong>Authorization: </strong>Bearer <i>* generated token access via /user/token endpoint</i></a><br/>
                    <strong>Requires: </strong>user_id<br/>
                    <strong>Requires: </strong>player_id<br/>
                </div>
                <div class="endpoints">
                    <span class="endpoint">Player wellness ( Create )</span><br/>
                    <strong>Method: </strong>POST<br/>
                    <strong>Url: </strong>http://localhost/api/v1/wellness</br>
                    <strong>Authorization: </strong>Bearer <i>* generated token access via /user/token endpoint</i></a><br/>
                    <strong>Header: </strong>Content-Type:application-json<br/>
                    <strong>Body: </strong>{"user_id":user_id,"sleep":(-1 to 1),"soreness":(-1 to 1),"fatigue":(-1 to 1)}<br/>
                </div>
                <div class="endpoints">
                    <span class="endpoint">Player wellness ( Update )</span><br/>
                    <strong>Method: </strong>PUT<br/>
                    <strong>Url: </strong>http://localhost/api/v1/wellness/{player_id}</br>
                    <strong>Authorization: </strong>Bearer <i>* generated token access via /user/token endpoint</i></a><br/>
                    <strong>Header: </strong>Content-Type:application-json<br/>
                    <strong>Body: </strong>{"sleep":(-1 to 1),"soreness":(-1 to 1),"fatigue":(-1 to 1)}<br/>
                </div>
            </ul>
        </div>
    </body>
</html>
