version: '2'

volumes:
    logs:
        driver: local

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: catapult
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8001:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
