version: '2'

volumes:
    logs:
        driver: local

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: catapult
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
    php:
        build: .
        working_dir: /var/www
        volumes_from:
            - code
    web:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
            - db
        volumes:
            - ./sites:/etc/nginx/conf.d
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        volumes_from:
            - code
    code:
        image: busybox
        volumes:
            - ./:/var/www
